import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/providers/CartProvider";
import Header from "@/components/Header";
import CommandPalette from "@/components/CommandPalette";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="zh-CN">
      <body className="bg-gray-50 text-gray-900">
        <CartProvider>
          {/* 顶部导航栏 */}
          <Header />

          {/* 页面内容 */}
          <main className="mx-auto max-w-6xl px-6 py-8">
            {children}
            {/* 放在 body 底部即可 */}
            {/* <CommandPalette /> */}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}